name: Test & Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [ "staging" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

  deploy:
    name: deploy
    needs: test
